# Generated by Django 4.1 on 2022-10-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
